from __future__ import annotations

from datetime import date
from html import escape

from .transition_report import PortfolioRow, portfolio_payload


def _text(value: object) -> str:
    text = str(value).strip() if value is not None else ""
    return escape(text or "—")


def render_client_html(
    rows: list[PortfolioRow],
    *,
    as_of: date,
    title: str = "ClinicOps Portfolio Transition Brief",
) -> str:
    """Render a self-contained client-facing HTML projection of the portfolio contract.

    The report is deliberately static and dependency-free so it can be shared through a
    controlled client workspace today and placed behind an authenticated portal later.
    """

    payload = portfolio_payload(rows, as_of=as_of)
    summary = payload["summary"]
    payload_rows = payload["rows"]
    limitations = payload["limitations"]

    table_rows: list[str] = []
    for row in payload_rows:
        source = str(row["source_url"]).strip()
        source_html = (
            f'<a href="{escape(source, quote=True)}" rel="noopener noreferrer">source</a>'
            if source
            else "—"
        )
        table_rows.append(
            "<tr>"
            f"<td>{_text(row['priority_score'])}</td>"
            f"<td>{_text(row['company'])}</td>"
            f"<td>{_text(row['device'])}</td>"
            f"<td>{_text(row['actor_role'])}</td>"
            f"<td>{_text(row['registration_type'])}</td>"
            f"<td>{_text(row['certificate_expiry'])}</td>"
            f"<td>{_text(row['danish_market'])}</td>"
            f"<td>{_text(row['workstream'])}</td>"
            f"<td>{source_html}</td>"
            "</tr>"
        )

    limitations_html = "".join(f"<li>{_text(item)}</li>" for item in limitations)
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{escape(title)}</title>
<style>
body {{ font-family: Arial, sans-serif; max-width: 1180px; margin: 0 auto; padding: 32px; line-height: 1.5; }}
h1, h2 {{ line-height: 1.2; }}
.notice {{ border: 1px solid #777; padding: 12px 16px; margin: 20px 0; }}
.summary {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 12px; margin: 20px 0; }}
.summary section {{ border: 1px solid #bbb; padding: 12px; }}
.summary strong {{ display: block; font-size: 1.5rem; }}
table {{ width: 100%; border-collapse: collapse; font-size: 0.92rem; }}
th, td {{ border: 1px solid #bbb; padding: 8px; text-align: left; vertical-align: top; }}
th {{ font-weight: 700; }}
footer {{ margin-top: 36px; font-size: 0.9rem; }}
@media print {{ body {{ max-width: none; padding: 12mm; }} a {{ color: inherit; text-decoration: none; }} }}
</style>
</head>
<body>
<header>
<h1>{escape(title)}</h1>
<p><strong>As of:</strong> {as_of.isoformat()}</p>
<div class="notice">Work-plan screening from supplied or public metadata. Priority is operator triage only; this report is not a compliance determination, legal conclusion, or full-register EUDAMED audit.</div>
</header>

<h2>Portfolio snapshot</h2>
<div class="summary">
<section><strong>{summary['records_reviewed']}</strong>records reviewed</section>
<section><strong>{summary['manufacturer_legacy']}</strong>legacy / legacy-screened MF records</section>
<section><strong>{summary['manufacturer_mdr_non_legacy']}</strong>MDR / non-legacy MF records</section>
<section><strong>{summary['procedure_pack_role']}</strong>PR / system-procedure-pack records</section>
<section><strong>{summary['danish_market_confirmed']}</strong>confirmed Danish-market rows</section>
</div>

<h2>Prioritised work plan</h2>
<table>
<thead><tr><th>Priority</th><th>Company</th><th>Device</th><th>Role</th><th>Registration</th><th>Certificate expiry</th><th>Danish market</th><th>Workstream</th><th>Evidence source</th></tr></thead>
<tbody>{''.join(table_rows)}</tbody>
</table>

<h2>Interpretation constraints</h2>
<ul>{limitations_html}</ul>

<h2>Recommended next questions</h2>
<ol>
<li>Which legacy manufacturer-role devices have the earliest verified certificate or transition dates?</li>
<li>Which of those devices are confirmed for the relevant target market?</li>
<li>Who owns Basic UDI-DI, SS(C)P, market-language availability and change-control work for each transition?</li>
<li>Which evidence is already controlled internally and which must be obtained from the manufacturer, authorised representative or notified body?</li>
</ol>

<footer>Generated by ClinicOps from the validated portfolio bundle contract. Human regulatory review remains required before external reliance on device-specific conclusions.</footer>
</body>
</html>
"""
